version: '3.1'
services:
  neo4j:
    image: neo4j:3.5
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .neo4j/data:/data
      - .:/var/lib/neo4j/import
      - ./neo4j-plugins:/plugins
    environment:
      - NEO4J_dbms_memory_heap_initial__size=3G
      - NEO4J_dbms_memory_heap_max__size=6G

  mongo:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .mongo:/data
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
